#+TITLE: Build Your Own Lisp Tutorial
#+AUTHOR: RAHUL SARAF
#+EMAIL: rahuketu86@gmail.com
#+TODO: TODO IN-PROGRESS WAITING DEFFERED DONE

* INTRODUCTION
  This is an exercise in learning multiple things. The objective is manifold :-
  - Learning Org Mode
  - Principles of Literate Programming
  - Learning C
  - Learning a way to implement a new language
  - Learning Lisp
  - And in doing all this - Learning Emacs :)
  
  Long term Goal include:-
  - Learning a method to implement extensible software and organization of software project
  - May be someday an editor like Emacs in Rust/Haskell

  So Stage has been set. Lets' get the ball rolling ...

* SETUP
  I will be following the wonderful tutorial at [[http://www.buildyourownlisp.com][buildyourownlisp.com]] . The basic idea would be to 
  write some code following the tutorial in literate mode and add some accompanying notes :-
  - Learnings :: Things that I have learned.
  - Questions :: Any questions I have.
  - Ideas  :: Some Ideas and thoughts for the future. 
